Repository virtualmarvin/web, pull requests merged in 2022-10, with the labels that each got.

#43 Feature/serilogging
  README.md
  src/Marvin.Web/Marvin.Web.csproj
  src/Marvin.Web/Program.cs
  src/Marvin.Web/appsettings.json
Labels: Technical

#44 Add Flat Areas and Routing
  src/Marvin.Web/Areas/Home/Error.cshtml
  src/Marvin.Web/Areas/Home/Error.cshtml.cs
  src/Marvin.Web/Areas/Home/Index.cshtml
  src/Marvin.Web/Areas/Home/Privacy.cshtml
  src/Marvin.Web/Areas/Home/Privacy.cshtml.cs
  src/Marvin.Web/Areas/Identity/Pages/_LoginPartial.cshtml
  src/Marvin.Web/Areas/Identity/Pages/_ViewStart.cshtml
  src/Marvin.Web/Areas/Landing/Index.cshtml
  src/Marvin.Web/Areas/Landing/LandingController.cs
  src/Marvin.Web/Areas/_Base/_Layout.cshtml
  src/Marvin.Web/Areas/_Base/_Layout.cshtml.css
  src/Marvin.Web/Areas/_Base/_LoginPartial.cshtml
  src/Marvin.Web/Areas/_Base/_ValidationScriptsPartial.cshtml
  src/Marvin.Web/Areas/_ViewImports.cshtml
  src/Marvin.Web/Areas/_ViewStart.cshtml
  src/Marvin.Web/Code/FlatAreas/FlatAreaConvention.cs
  src/Marvin.Web/Code/FlatAreas/FlatAreaExpander.cs
  src/Marvin.Web/Code/FlatAreas/FlatAreaExtensions.cs
  src/Marvin.Web/Code/FlatAreas/FlatAreaOptions.cs
  src/Marvin.Web/Marvin.Web.csproj
  src/Marvin.Web/Pages/Index.cshtml.cs
  src/Marvin.Web/Program.cs
  src/Marvin.Web/ScaffoldingReadMe.txt
Labels: Technical

#49 Feature/42 swagger man
  README.md
  docs/.img/vs-documentation-properties.png
  src/Marvin.Web/Areas/Home/V1/HomeController.cs
  src/Marvin.Web/Areas/Home/V1/Order.cs
  src/Marvin.Web/Areas/Home/V2/HomeController.cs
  src/Marvin.Web/Areas/Home/V2/Order.cs
  src/Marvin.Web/Code/Bootstrap/Database.cs
  src/Marvin.Web/Code/Bootstrap/Swagger.cs
  src/Marvin.Web/Code/Swagger/ConfigureSwaggerOptions.cs
  src/Marvin.Web/Code/Swagger/SwaggerDefaultValues.cs
  src/Marvin.Web/Marvin.Web.csproj
  src/Marvin.Web/Program.cs
Labels: documentation, Technical

#48 Just a little example of funcsharp
  src/Marvin.Web/Code/FlatAreas/FlatAreaExpander.cs
  src/Marvin.Web/Code/FlatAreas/FlatAreaExtensions.cs
Labels: documentation, Technical

#50 Fix The Privacy Page and Wire Up to HomeController
  src/Marvin.Web/Areas/Home/HomeController.cs
  src/Marvin.Web/Areas/Home/Index.cshtml
  src/Marvin.Web/Areas/Home/Privacy.cshtml
  src/Marvin.Web/Areas/Landing/Index.cshtml
  src/Marvin.Web/Areas/_Base/_Layout.cshtml
  src/Marvin.Web/Program.cs
Labels: bug, documentation

#51 Fixed the Error page and correct some routes
  src/Marvin.Web/Areas/Home/Error.cshtml
  src/Marvin.Web/Areas/Home/ErrorViewModel.cs
  src/Marvin.Web/Areas/Home/HomeController.cs
  src/Marvin.Web/Areas/_Base/_Layout.cshtml
  src/Marvin.Web/Program.cs
Labels: Technical

#53 Hashids and Nuget fixes
  README.md
  src/Marvin.Web/Areas/Home/V2/HomeController.cs
  src/Marvin.Web/Areas/Home/V2/Order.cs
  src/Marvin.Web/Code/Bootstrap/Database.cs
  src/Marvin.Web/Code/Bootstrap/DatabaseBootstrap.cs
  src/Marvin.Web/Code/Bootstrap/HashIdsBootstrap.cs
  src/Marvin.Web/Code/Bootstrap/HashidOptions.cs
  src/Marvin.Web/Code/Bootstrap/SwaggerBootstrap.cs
  src/Marvin.Web/Marvin.Web.csproj
  src/Marvin.Web/Program.cs
  src/Marvin.Web/appsettings.json
Labels: documentation, Technical

#56 Feature/object extentions
  README.md
  src/Marvin.Tests/Marvin.Web.Tests/Code/Exceptions/MultiExceptionTests.cs
  src/Marvin.Tests/Marvin.Web.Tests/Code/Validators/ValidationTests.cs
  src/Marvin.Tests/Marvin.Web.Tests/Marvin.Web.Tests.csproj
  src/Marvin.Tests/Marvin.Web.Tests/Usings.cs
  src/Marvin.Web/Areas/Identity/Pages/Account/ExternalLogin.cshtml.cs
  src/Marvin.Web/Code/Exceptions/MultiException.cs
  src/Marvin.Web/Code/Exceptions/ValidationException.cs
  src/Marvin.Web/Code/Extensions/ObjectExtensions.cs
  src/Marvin.Web/Code/FlatAreas/FlatAreaConvention.cs
  src/Marvin.Web/Code/FlatAreas/FlatAreaExpander.cs
  src/Marvin.Web/Code/Validators/Validation.cs
  src/Marvin.Web/Code/Validators/ValidationExtentions.cs
  src/Marvin.Web/Marvin.Web.sln
Labels: Technical
